### ISSUE TITLE
Indicate year of data presented

### ISSUE THREAD

**Issue by manicplanet** [joellastraley/spi-scorecards#12]

**Comment by joellastraley** [comment]
I've added a note in the footer that this is from the 2015 index. If this comment is directed at the individual indicators, I think this should fold into the discussion of how much information to include about the indicators and how to surface it for which audiences. For example, perhaps these details could be revealed on mouseover. Or, to accommodate the need for print & slide products coming out of this, I could imagine have a detailed/non-detailed view. There are a lot of possibilities on this issue, so let's talk about what's best for our audience needs.
